import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Manrope, Fjalla_One } from 'next/font/google';
import './globals.css';
import { Providers } from '@components/Providers';
import { Navigation } from '@components/Navigation';
import clsx from 'clsx';

const manrope = Manrope({ subsets: ['latin'] });

const fjallaOne = Fjalla_One({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={clsx(fjallaOne.className, manrope.className)}>
          <Navigation />
          {children}
        </body>
      </html>
    </Providers>
  );
}
