import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Manrope, Fjalla_One } from 'next/font/google';
import './globals.css';
import { Providers } from '@components/Providers';
import { Navigation } from '@components/Navigation';
import clsx from 'clsx';

const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });
const fjallaOne = Fjalla_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-fjalla',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={clsx(manrope.variable, fjallaOne.variable)}>
          <Navigation />
          {children}
        </body>
      </html>
    </Providers>
  );
}
